config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :user do 
    get '/users/sign_in' , to: 'devise/sessions#new', :as => :login
  end
  devise_for :users, skip: :all
  resources :admins do
    collection do
      get :charge_user
    end
  end
  resources :buyers
  resources :usages
  resources :plans do
  	resources :features
  end
  resources :plans do
    resources :subscriptions
  end
  resources :users do
    resources :subscriptions
  end
  resources :users do
    resources :transactions
  end
  root to: 'home#index'
end  

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  has_many :usages , dependent: :destroy

  after_create :send_user_mail

  def send_user_mail
  	UserMailer.send_welcome_email(self).deliver_later
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :authenticate_user!
  def index
    @user = User.find (params[:user_id])
  end
	
  def create
    @plan = Plan.find (params[:plan_id])
    @subscription = @plan.subscriptions.new(user_id: current_user.id , plan_id: @plan.id)
    ActiveRecord::Base.transaction do
      if @subscription.save
        Transaction.create(payment_date: Date.today.day , month: Date.today.year , year: Date.today.year, resource_id: '1',resource_type: "Subscription" , charge_type: "Subscription", bill_status: "active", total_charges:@plan.fee)
        redirect_to "/buyers"
      else
        render plain: "No Subscription and No Transaction"
      end
    end
	end

  def show
    @plan = Plan.find(params[:plan_id])
    @subscription = Subscription.find(params[:id])
  end
  
  def new
    @subscription = Subscription.new(subscription_params)
  end
  
  def edit
    @subscription = Subscription.find(params[:id])
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    redirect_to plan_subscriptions_path(@plan)
  end  

  private
    def subscription_params
      params.require(:subscription).permit(:user_id, :plan_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing All Subscriptions of <%= @user.username %> </h1>


<table>
  <tr>
    <th>User ID</th>
    <th>Plan ID</th>
    <th colspan="2"></th>
  </tr>
 
  <% @user.subscriptions.each do |subscription| %>
   
      <tr>
        <td><%= subscription.user_id %></td>
        <td><%= subscription.plan_id %></td>
      </tr>
    
  <% end %>
</table>
<br>
<li><%= link_to 'Back', buyers_path %></li>

app/views/subscriptions/new.html.erb
<h1>Add New Subscription</h1>

<%= form_with scope: :subscription, url: plan_subscriptions_path(@plan.id), local: true do |form| %>
  <p>
    <%= form.label :user_id %>
    <%=  current_user.id %>
  </p>
 
  <p>
    <%= form.label :plan_id %>
    <%= form.text_field :plan_id %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', plan_subscriptions_path(@plan.id) %>

app/views/subscriptions/show.html.erb
<% @plan.subscriptions.each do |subscription| %>
  <p>
    <strong>User ID:</strong>
    <%= @subscription.user_id %>
  </p>
  <p>
    <strong>Plan ID:</strong>
    <%= @subscription.plan_id %>
  </p>
<% end %>