config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :user do 
    get '/users/sign_in' , to: 'devise/sessions#new', :as => :login
  end
  devise_for :users, skip: :all
  resources :admins do
    collection do
      get :charge_user
    end
  end
  resources :buyers
  resources :usages
  resources :plans do
  	resources :features
  end
  resources :plans do
    resources :subscriptions
  end
  resources :users do
    resources :subscriptions
  end
  resources :users do
    resources :transactions
  end
  root to: 'home#index'
end  

app/models/admin.rb
class Admin < ApplicationRecord
  def self.make_payment
    User.find_each do |user|
      calculate_payment(user)
    end
  end

  private

  def calculate_payment(user)
    subscriptions = user.subscriptions
    plan = Plan.find(subscriptions.pluck(:plan_id))
    plan_fee = plan.fee
    usages = subscription.usages.all
    extraunits = usages.pluck(:no_of_units_used)
    features = Feature.find(usages.pluck(:feature_id))
    featureunits = features.pluck(:max_unit_limit)
    unitprice = features.pluck(:unit_price)
    if extraunits > featureunits
      eunits = extraunits - featureunits
      feature_overuse = eunits * unitprice
      plan_fee = plan_fee + feature_overuse
    else
      plan_fee = plan_fee
    end

    Transaction.create( payment_date: user.billday  , total_charges: plan_fee  , month: usage.month, year: usage.year, charge_type: "Subscription" )
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :plan
  has_many :usage
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :features
	has_many :subscriptions
	validates :name, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  has_many :usages , dependent: :destroy

  after_create :send_user_mail

  def send_user_mail
  	UserMailer.send_welcome_email(self).deliver_later
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
   belongs_to :user
end

app/models/usage.rb
class Usage < ApplicationRecord
  belongs_to :feature
  belongs_to :subscription
  validates :no_of_units_used, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :subscriptions
  has_many :transactions
  validates :username, presence: true, length: { minimum: 4 ,  maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, stretches: 13
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all
  end
  
  def show
    @users = User.all
  end
  
  def charge_user
    Admin.make_payment
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(admin_params)
    if @user.save
      if @user.usertype = 'User'
        render "buyers/show"
      else
        redirect_to @admin
      end
    else
      render plain: "Not Successfully Registered"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
   #redirect_to 'devise/session/user'
  end

  private
    def admin_params
      params.require(:user).permit(:email, :username, :billday)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery 
	include Pundit
  #rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  #after_action :verify_authorized, except: :index
  #after_action :verify_policy_scoped, only: :index
  
  protected

  def configure_permitted_parameters
  added_attrs = [:username, :email, :password, :password_confirmation, :billday, :usertype]
	devise_parameter_sanitizer.permit :sign_up, keys: added_attrs 
  devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
  def after_sign_in_path_for(resource)
    if current_user.usertype == "User"
      buyer_path(current_user.id)
    else
      admins_path
    end
  end

  #rescue_from Pundit::NotAuthorizedError do 
   # redirect_to root_url , alert: "You do not have access to this page"  
  #end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
	before_action :authenticate_user!

  def index
    @plans = Plan.all
	end
	
  def show
    @subscriptions = Subscription.all
		@plans = Plan.all
	end
  
  def after_sign_out_path_for(resources)
    new_user_session_path
  end
  
  def create
    @plan = Plan.find (params[:plan_id])
    @subscription = @plan.subscriptions.new(user_id: current_user.id , plan_id: @plan.id)
    ActiveRecord::Base.transaction do
      if @subscription.save
        Transaction.create(payment_date: Date.today.day , month: Date.today.year , year: Date.today.year, resource_id: '1',resource_type: "Subscription" , charge_type: "Subscription", bill_status: "active", total_charges:@plan.fee)
        redirect_to "/buyers"
      else
        render plain: "No Subscription and No Transaction"
      end
    end
  end

  private
    
  def plan_params
    params.require(:plan).permit(:name, :fee)
  end

  def subscription_params
    params.require(:subscription).permit(:user_id, :plan_id)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  def index
    @plan = Plan.find(params[:plan_id])
  	@features = @plan.features.all
  end
  def new
    
    @plan = Plan.find(params[:plan_id])
    @feature = Feature.new
  end
  def update
    @feature = Feature.find(params[:id])
    if @feature.update(feature_params)
      redirect_to @feature
    else
      render 'edit'
    end
  end
  def home
    @feature = Feature.find(params[:id])
  end

  def show
    @plan = Plan.find(params[:plan_id])
    @feature = Feature.find(params[:id])
  end
  
  def create
    
  	@plan = Plan.find(params[:plan_id])
  	@feature = @plan.features.create(feature_params)
	  redirect_to plan_path(@plan)
  end

  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy
    redirect_to features_path
  end

  private
    def feature_params
      params.require(:feature).permit(:name, :code, :unit_price, :max_unit_limit, :plan_id)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
	#before_action :user_is_required, only: [:create, :update, :destroy]
  before_action :authenticate_user!
  def index
    @plans = Plan.all
	end
	
  def create
		@plan = Plan.new(plan_params)
		if @plan.save
		  redirect_to @plan
    else
      render 'new'
    end
	end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to @plan
    else
      render 'edit'
    end
  end
  
  def show
    @plan = Plan.find(params[:id])
  end
  
  def new
    @plan = Plan.new
  end
  
  def edit
    @plan = Plan.find(params[:id])
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  private
    def plan_params
      params.require(:plan).permit(:name, :fee)
    end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :authenticate_user!
  def index
    @usages = Usage.all
	end

	
  def update
    @usage = Usage.find(params[:id])
    if @usage.update(usage_params)
      redirect_to @usage
    else
      render 'edit'
    end
  end

  def show
    @usage = Usage.find(params[:id])
  end

  def new
    @usage = Usage.new
  end
  
  def edit
    @usage = Usage.find(params[:id])
  end

  def create
		@usage = Usage.new(usage_params)
    if @usage.save
      redirect_to @usage
    else
      render 'new'
    end
	end

  private
    def usage_params
      params.require(:usage).permit(:no_of_units_used, :month, :year, :feature_id, :subscription_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyer_helper.rb
module BuyerHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/features/index.html.erb
<h1>Listing All Features of <%=@plan.name%> </h1>
<% @plan.features.each do |feature| %>
  <p>
    <strong>Feature Name:</strong>
    <%= feature.name %><br>
    <strong>Feature Code:</strong>
    <%= feature.code %><br>
    <strong>Feature Unit Price:</strong>
    <%= feature.unit_price %><br>
    <strong>Feature Max Unit Limit:</strong>
    <%= feature.max_unit_limit %><br>
  </p>
 
<% end %>

<li><%= link_to 'Add New Feature', new_plan_feature_path(@plan.id)  %></li>
<li><%= link_to 'Back', plan_path(@plan.id) %></li>

app/views/features/new.html.erb
<h2>Add a Feature:</h2>
<%= form_with scope: :feature, url: plan_features_path(@plan.id), local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :code %><br>
    <%= form.text_field :code %>
  </p>
  <p>
    <%= form.label :unit_price %><br>
    <%= form.text_field :unit_price %>
  </p>
  <p>
    <%= form.label :max_unit_limit %><br>
    <%= form.text_field :max_unit_limit %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', plan_features_path(@plan.id) %>

app/views/features/show.html.erb
<% @plan.features.each do |feature| %>
<p>
  <strong>Name:</strong>
  <%= @feature.name %>
</p>
<p>
<strong>Code:</strong>
  <%= @feature.code %>
</p>
<strong>Unit Price:</strong>
  <%= @feature.unit_price %>
</p>
<strong>Max Unit Limit:</strong>
  <%= @feature.max_unit_limit %>
</p>
<% end %>

app/views/plans/edit.html.erb
<h1>Edit Plan</h1>
 
 <%= form_with(model: @plan, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :fee %><br>
    <%= form.text_field :fee %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
  <% end %>
 
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing All Plans</h1>
 

<%= link_to 'New Plan', new_plan_path %>
<br>
<table>
  <tr>
    <th>Name</th>
    <th>Fee</th>
    <th colspan="2"></th>
  </tr>
 
  <% @plans.each do |plan| %>
    <tr>
      <td><%= plan.name %></td>
      <td><%= plan.fee %></td>
      <td><%= link_to 'Show', plan_path(plan) %></td>
      <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
    </tr>
  <% end %>
</table>
<br>

<li><%= link_to 'Back', admins_path %></li>

app/views/plans/new.html.erb
<h1>Add New Plan</h1>

<%= form_with scope: :plan, url: plans_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :fee %><br>
    <%= form.text_field :fee %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back to Main Page', plans_path %>
<h1> Show Plan </h1>
<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>
<p>
  <strong>Fee:</strong>
  <%= @plan.fee %>
</p>
<%= link_to 'Show All Features', plan_features_path(@plan.id) %>
<br>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/usages/edit.html.erb
<h1>Edit Usage</h1>
 
 <%= form_with(model: @usage, local: true) do |form| %>
  <p>
    <%= form.label :no_of_units_used %><br>
    <%= form.text_field :no_of_units_used %>
  </p>
 
  <p>
    <%= form.label :month %><br>
    <%= form.text_field :month %>
  </p>
  <p>
    <%= form.label :year %><br>
    <%= form.text_field :year %>
  </p>
   <p>
    <%= form.label :feature_id %><br>
    <%= form.text_field :feature_id %>
  </p>
  <p>
    <%= form.label :subscription_id %><br>
    <%= form.text_field :subscription_id %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
  <% end %>
 
<%= link_to 'Back', usages_path %>

app/views/usages/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Usage', new_usage_path %>
<h1>Listing All Usages</h1> 
<table>
  <tr>
    <th>Number of units used</th>
    <th>Month</th>
    <th>Year</th>
    <th>Feature ID</th>
    <th>Subscription ID</th>
    <th colspan="2"></th>
  </tr>
 
  <% @usages.each do |usage| %>
    <tr>
      <td><%= usage.no_of_units_used %></td>
      <td><%= usage.month %></td>
      <td><%= usage.year %></td>
      <td><%= usage.feature_id %></td>
      <td><%= usage.subscription_id %></td>
      <td><%= link_to 'Show', usage_path(usage) %></td>
      <td><%= link_to 'Edit', edit_usage_path(usage) %></td>
    </tr>
  <% end %>
</table>
<br>

<li><%= link_to 'Back', admins_path %></li>

app/views/usages/new.html.erb
<h1>Add New Usage </h1>

<%= form_with scope: :usage, url: usages_path , local: true do |form| %>
  <p>
    <%= form.label :no_of_units_used %><br>
    <%= form.text_field :no_of_units_used %>
  </p>
 
  <p>
    <%= form.label :month %><br>
    <%= form.text_field :month %>
  </p>
  <p>
    <%= form.label :year %><br>
    <%= form.text_field :year %>
  </p>
   <p>
    <%= form.label :feature_id %><br>
    <%= form.text_field :feature_id %>
  </p>
  <p>
    <%= form.label :subscription_id %><br>
    <%= form.text_field :subscription_id %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', usages_path %>

app/views/usages/show.html.erb
<%= link_to 'Back to Main Page', usages_path %>
<h1> Show Usage Table </h1>
<p>
  <strong>No of units used</strong>
  <%= @usage.no_of_units_used%>
</p>
 
<p>
  <strong>Month:</strong>
  <%= @usage.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @usage.year %>
</p>
<p>
  <strong>Feature ID:</strong>
  <%=@usage.feature_id  %>
</p>
<p>
  <strong>Subscription ID:</strong>
  <%=@usage.subscription_id  %>
</p>
<p>
<%= link_to 'Back', usages_path %>